name: Build Project

on:
  push:
    branches: ['master']

jobs:
  build:
    name: Build Java Project
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      
      - name: Use Node.js 20.x
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'
      
      - name: Build with Maven
        run: mvn clean install
